config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/profile', to: 'pages#profile'
  get '/my_petitions', to: 'pages#my_petitions', as: "my_petitions"
  get "/my_sites", to: "pages#my_sites"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :collectors, only: %i[index show]
  resources :recycling_sites
  resources :petitions, only: %i[index create]
  patch "petitions/:id/accept", to: "petitions#accept_petition", as: "accept_petition"
  patch "petitions/:id/decline", to: "petitions#decline_petition", as: "decline_petition"
  patch "petitions/:id/do", to: "petitions#do_petition", as: "do_petition"
  patch "petitions/:id/accept_petition_site", to: "petitions#accept_petition_site", as: "accept_petition_site"
  patch "petitions/:id/decline_petition_site", to: "petitions#decline_petition_site", as: "decline_petition_site"
end

app/views/pages/home.html.erb
<% page_heading "Recicla, reusa y ayuda al futuro" %>
<div class="ciclico-background d-flex flex-column justify-content-between" style="background: linear-gradient(rgba(0,0,0,0.5),rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1525695230005-efd074980869?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1374&q=80) center;">
  <%= render 'shared/navbar_home' %>
  <div class="banner flex-grow-1">
    <div class="container text-secondary text-center py-4">
      <h1>Haz parte del <i>ciclo</i></h1>
        <div class="footer-copyright text-secondary fs-4">
          <h2>¡Recicla, reúsa y ayuda al futuro!</h2>
        </div>
      <h3 class="mt-2 mb-4">¿Qué quieres hacer con tu reciclaje?</h3>
      <%= link_to "Llévalo tu mismo", recycling_sites_path(@recycling_site), class: "btn-info-ciclico m-3 rounded-pill text-secondary px-4" %>
      <%= link_to "Ver recolectores", collectors_path(@collector), class: "btn-info-ciclico m-3 rounded-pill text-secondary px-4" %>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/pages/my_petitions.html.erb
  <% page_heading "Mis peticiones" %>
  <div class="ciclico-gradient-show d-flex flex-column justify-content-between">
  <%= render 'shared/navbar' %>
  <div class="container text-secondary bg-primary rounded-5 px-5 flex-grow-1">
    <div class="tabs my-5">
      <div class="tab">
        <input type="radio" name="css-tabs" id="tab-1" checked class="tab-switch">
        <label for="tab-1" class="tab-label rounded-pill me-2 fs-5">Peticiones pendientes</label>
        <div class="tab-content mt-4 rounded-5 row" id="profile-scroll">
          <% if Petition.where(collector: current_user, status: 0).empty? %>
            <h3 class="text-info text-center">No tienes peticiones nuevas</h3>
          <% end %>
          <div class="mt-3 row">
            <% Petition.where(collector: current_user, status: 0).each do |petition| %>
              <div class="col-4">
                <div class="card bg-transparent border-info ms-3 mb-3 rounded-5" style="max-width: 18rem;">
                  <div class="card-header rounded-top bg-transparent">
                    <h4 class="text-success mt-2 text-center"> <b><%= petition.user.first_name %></b></h4>
                  </div>
                  <div class="card-body text-success">
                    <p class="card-text">
                      Te realizó una petición para recoger <i><%= petition.material.category %></i> el <%= petition.date %> en la siguiente ubicación: </p>
                      <%= petition.address.address %>
                      <div class="d-flex">
                        <%= link_to "Rechazar", decline_petition_path(petition), data: {turbo_method: :patch }, class:"btn btn-primary me-3 rounded-pill text-secondary" %>
                        <%= link_to "Aceptar", accept_petition_path(petition), data: {turbo_method: :patch }, class:"btn btn-primary rounded-pill text-secondary" %>
                      </div>
                    </p>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="tab">
        <input type="radio" name="css-tabs" id="tab-2" class="tab-switch">
        <label for="tab-2" class="tab-label rounded-pill me-2 fs-5">Peticiones aceptadas</label>
        <div class="tab-content mt-4 rounded-5">
          <div class="mt-3 row">
            <% if Petition.where(collector: current_user, status: 1).empty? %>
              <h3 class="text-info text-center">No tienes peticiones aceptadas</h3>
            <% end %>
            <div class="mt-3 row">
              <% Petition.where(collector: current_user, status: 1).each do |petition| %>
                <div class="col-6">
                  <div class="card bg-transparent border-info ms-3 mb-3 rounded-5" style="max-width: 30rem;">
                    <div class="card-header rounded-top bg-transparent">
                      <h4 class="text-success mt-2 text-center"> <b><%= petition.user.first_name %></b></h4>
                    </div>
                    <div class="card-body text-success">
                      <p class="card-text">
                        Te realizó una petición para recoger <i><%= petition.material.category %></i> el <%= petition.date %> en la siguiente ubicación: <%= petition.address.address %> <br>
                        Por favor asiste a tiempo, en caso de no poder cumplir por favor comunícate con <%= petition.user.first_name %> al correo <%= petition.user.email %>
                      </p>
                      <div class="text-center">
                        <%= link_to "Marcar como realizada", do_petition_path(petition), data: {turbo_method: :patch }, class:"btn btn-primary rounded-pill text-secondary" %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="tab">
        <input type="radio" name="css-tabs" id="tab-3" class="tab-switch">
        <label for="tab-3" class="tab-label rounded-pill me-2 fs-5">Recolecciones realizadas</label>
        <div class="tab-content mt-4 rounded-5">
          <div class="mt-3 row">
            <% if Petition.where(collector: current_user, status: 3).empty? %>
              <h3 class="text-info text-center">Todavía no has hecho ninguna recolección</h3>
            <% end %>
            <div class="mt-3 row">
              <% Petition.where(collector: current_user, status: 3).each do |petition| %>
                <div class="col-4">
                  <div class="card bg-transparent border-info ms-3 mb-3 rounded-5" style="max-width: 18rem;">
                    <div class="card-header rounded-top bg-transparent">
                      <h4 class="text-success mt-2 text-center"> <b><%= petition.user.first_name %></b></h4>
                    </div>
                    <div class="card-body text-success">
                      <p class="card-text">
                        Te realizó una petición para recoger <i><%= petition.material.category %></i> el <%= petition.date %> en la siguiente ubicación: </p>
                        <%#= petition.address.address %>
                        Asististe a tiempo y realizaste la recolección, muchas gracias!
                      </p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/pages/my_sites.html.erb
<% page_heading "Administrar Sitios de Reciclaje" %>
<div class="ciclico-gradient d-flex flex-column justify-content-between">
  <%= render 'shared/navbar' %>
<div class="container text-secondary bg-primary rounded-5 p-5 f-flex">
    <h1>Mis puntos de reciclajes</h1>
    <a type="button" class="btn btn-info rounded-pill mt-3" data-bs-toggle="modal" data-bs-target="#RecyclingModal">
      Agregar sitio de reciclaje
    </a>
    <div class="row">
      <div class="col-4">
        <% @recycling_sites.each do |site|  %>
            <%= link_to recycling_site_path(site), class: "text-decoration-none" do  %>
              <div class="card my-2">
                    <div class="card-body">

                      <h2><%= site.name.capitalize %></h2>
                    </div>
              </div>
            <% end %>
        <% end %>
      </div>

      <div class="col-8 ">
        <h3>Peticiones activas</h3>
        <hr>
        <div class="mt-3">
              <div class="d-flex-column">
              <% current_user.petitions.each do |petition| %>
                <% if petition.recycling_site_id != nil  %>
                  <p> Sitio de solictud : <%= RecyclingSite.where(id: petition.recycling_site_id).first.name %> </p>
                  <p></p><%=  %>
                  <p> Material : <%= RecyclingSite.where(id: petition.recycling_site_id).first.material.category %> </p>
                  <div class="d-flex">
                    <p class="me-2"> Estado: <% petition.status%>
                    <% if petition.pendiente? %>
                      <p>Pendiente </p>
                    <% elsif petition.aceptado? %>
                      <p>Aceptado</p>
                    <% elsif petition.rechazado?  %>
                      <p> Rechazado </p>
                    <% end %>
                  </div>
                  <div>
                    <% if petition.pendiente? %>
                      <%= link_to "Rechazar peticion", decline_petition_site_path(petition), data: {turbo_method: :patch }, class:"btn btn-primary" %>
                      <%= link_to "Aceptar peticion", accept_petition_site_path(petition), data: {turbo_method: :patch }, class:"btn btn-primary" %>
                    <% elsif petition.status = 0 %>
                      <p>Lo siento!! Intenta con otro sitio</p>
                    <% end %>
                  </div>
                <%end  %>
              <% end %>

              <hr>
        </div>
      </div>
    </div>
  </div>
</div>

  <%= render 'shared/footer' %>

<!-- Modal -->
<div class="modal fade" id="RecyclingModal" tabindex="-1" aria-labelledby="RecyclingModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content rounded-5 bg-secondary">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="RecyclingModalLabel">Agregar Sitio de Reciclaje</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for [@recycling_site] do |f| %>
        <div class="modal-body">
          <%= f.input :name, required: true %>
          <%= f.association :material, collection: Material.all, label_method: :category, required: true %>
          <%= f.input :description, required: true %>
          <%= f.simple_fields_for :addresses_data do |a| %>
            <%= a.input :address,
              input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
              wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
            %>
          <% end %>
          <%= f.input :photo, as: :file %>
        </div>
        <div class="modal-footer">
          <%= f.button :submit, "Agregar", class: "btn btn-primary mb-3" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/profile_collector.html.erb
  <div class="ciclico-gradient-show d-flex flex-column justify-content-between">
  <%= render 'shared/navbar' %>
  <div class="container text-secondary bg-primary rounded-5 p-5">
    <div class="row">
      <div class="col-8">

      <div class="col-4">
        <h3>Agendas para ti</h3>
        <hr>
        <div class="mt-3">
          <% Petition.where(collector: current_user).each do |petition| %>
            <p>Solicitante: <%= petition.user.first_name %></p>
            <p>Fecha: <%= petition.date %></p>
            <p>Material: <%= petition.material.category %></p>
            <div class="d-flex">
              <p class="me-2">Estado: </p>
              <% if petition.pendiente? %>
                <p>Pendiente </p>
              <% elsif petition.aceptado? %>
                <p>Aceptado</p>
              <% elsif petition.rechazado?  %>
                <p> Rechazado </p>
              <% end %>
            </div>
            <%# <%= link_to "Aceptar peticion", accept_petition_path(petition), data: {turbo_method: :patch }, class:"btn btn-primary" %>
            <%# <%= link_to "Rechazar peticion", decline_petition_path(petition), data: {turbo_method: :patch }, class:"btn btn-primary" %>
            <% if current_user.collector? %>
              <%= link_to "Rechazar peticion", decline_petition_path(petition), data: {turbo_method: :patch }, class:"btn btn-primary" %>
              <%= link_to "Aceptar peticion", accept_petition_path(petition), data: {turbo_method: :patch }, class:"btn btn-primary" %>
            <% end %>
            <hr>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<%= render 'shared/footer' %>