config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get '/profile', to: 'pages#profile'
  get '/my_petitions', to: 'pages#my_petitions', as: "my_petitions"
  get "/my_sites", to: "pages#my_sites"
  # Defines the root path route ("/")
  # root "articles#index"
  resources :collectors, only: %i[index show]
  resources :recycling_sites
  resources :petitions, only: %i[index create]
  patch "petitions/:id/accept", to: "petitions#accept_petition", as: "accept_petition"
  patch "petitions/:id/decline", to: "petitions#decline_petition", as: "decline_petition"
  patch "petitions/:id/do", to: "petitions#do_petition", as: "do_petition"
  patch "petitions/:id/accept_petition_site", to: "petitions#accept_petition_site", as: "accept_petition_site"
  patch "petitions/:id/decline_petition_site", to: "petitions#decline_petition_site", as: "decline_petition_site"
end

app/controllers/collectors_controller.rb
class CollectorsController < ApplicationController
  before_action :set_collector, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:city].present?
      @collectors = User.where(city: params[:city])
    else
      @collectors = User.where(collector: true)
    end
  end

  def show
    @petition = Petition.new
  end

  private

  def set_collector
    @collector = User.find(params[:id])
  end

end

app/views/collectors/index.html.erb
<% page_heading "Recolectores" %>
<div class="ciclico-gradient d-flex flex-column justify-content-between">
  <%= render 'shared/navbar' %>
  <div class="container mt-3">
    <h1 class="text-secondary text-center">Estos recicladores trabajan cerca a tí</h1>
    <%= form_with url: collectors_path, method: :get, class: "d-flex" do %>
      <%= select_tag :city,
        options_for_select([["Ciudad"], ["Medellín"], ["Envigado"], ["Itagüí"]]),
        class: "form-control",
        placeholder: "Looking your City"
      %>
        <%= submit_tag "Buscar", class: "btn btn-primary text-secondary" %>
      <% end %>
    <div class="row">
      <% @collectors.each do |collector| %>
        <div class="col-4">
          <%= link_to collector_path(collector), class: "text-decoration-none" do %>
            <div class="card my-2 rounded-5">
                  <% if collector.photo.attached? %>
                   <%= cl_image_tag collector.photo.key, style: "width:100%; height:235px", class: "rounded-5" %>
                  <% else %>
                   <%= image_tag "https://www.wiego.org/sites/default/files/Hewlett_Bogota_FullRelease_050_1.jpg", style: "width:100%; height:235px", class: "rounded-5" %>
                  <% end %>
                  <div class="card-body">
                    <h2><%= collector.first_name %></h2>
                    <h2><%= collector.city %></h2>
                  </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

app/views/collectors/show.html.erb
<% page_heading "#{@collector.first_name}" %>
<script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.min.js"></script>
<link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v5.0.0/mapbox-gl-geocoder.css" type="text/css">
<div class="ciclico-gradient-show d-flex flex-column justify-content-between">
  <%= render 'shared/navbar' %>
  <div class="container text-secondary bg-primary rounded-5 p-5">
    <div class="row">
      <div class="col-8">
        <div class="name d-flex">
          <h1> <%= @collector.first_name %></h1>
          <h1 class="text-warning ms-3"><%= @collector.last_name %></h1>
        </div>
        <h4>Horario: Lunes a Viernes 12:00 a 21:00</h4>
        <p>Trabajo principalmente por los barrios de El Dorado, Alcalá y El Portal en Envigado, recibo principalmente papel/cartón</p>
        <%= link_to "Regresar", collectors_path, class:"btn btn-success rounded-pill text-secondary" %>
      </div>
      <div class="col-4">
        <h3></h3>
        <h4><%#= @recycling_site.material.address %></h4>
        <div class="map">
          <% if @collector.photo.attached? %>
                   <%= cl_image_tag @collector.photo.key, style: "width: 100%; height:250px"%>
                  <% else %>
                   <%= image_tag "https://www.wiego.org/sites/default/files/Hewlett_Bogota_FullRelease_050_1.jpg", style: "width:100%; height:250px"%>
                  <% end %>
        </div>
        <div class="mt-3">
          <%= simple_form_for @petition do |f|%>
            <%= f.input :status, as: :hidden, value: 0  %>
            <%= f.datetime_select :date %>
            <%= f.association :material, collection: Material.all, label_method: :category %>
            <%= hidden_field_tag 'collector_id', @collector.id %>
            <%= f.simple_fields_for :addresses_data do |a| %>
              <%= a.input :address,
                input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
              %>
            <% end %>
            <%= f.submit "Programar recogida", class:"btn btn-success rounded-pill text-secondary mt-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>